server:
  port: 8020
spring:
  application:
    name: seckill-service
  datasource: #数据源配置
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///0522db?useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  redis: #redis配置
    host: 127.0.0.1 # 设连接地址
    port: 6379 # 端口号
    database: 1 # 放到几号口
  cloud:
    nacos: #nacos配置
      discovery:
        server-addr: 127.0.0.1:8848
feign: #feign配置
  sentinel:
    enabled: true #开启feign的sentinel
mybatis-plus: #mybatis-plus配置
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #打印sql日志
    map-underscore-to-camel-case: true #关闭下划线转驼峰命名
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.zt.bean